import { TYPE_ANALYZE, TYPE_SUM, TYPE_TRANSLATE, TYPE_TRANSLATE_DOWN } from '../../constants/command.js';
import COMMAND_ANALYZE_ANALYZE from './analyze-analyze.js';
import COMMAND_ANALYZE_LITERARILY from './analyze-literarily.js';
import COMMAND_ANALYZE_MATHEMATICALLY from './analyze-mathematically.js';
import COMMAND_ANALYZE_NUMEROLOGICALLY from './analyze-numerologically.js';
import COMMAND_ANALYZE_PHILOSOPHICALLY from './analyze-philosophically.js';
import COMMAND_ANALYZE_PSYCHOLOGICALLY from './analyze-psychologically.js';
import COMMAND_BOT_ACTIVATE from './bot-activate.js';
import COMMAND_BOT_CONTINUE from './bot-continue.js';
import COMMAND_BOT_DEACTIVATE from './bot-deactivate.js';
import COMMAND_BOT_DRAW_DEMO from './bot-draw-demo.js';
import COMMAND_BOT_DRAW from './bot-draw.js';
import COMMAND_BOT_FORGET from './bot-forget.js';
import COMMAND_BOT_RETRY from './bot-retry.js';
import COMMAND_BOT_SEARCH from './bot-search.js';
import COMMAND_BOT_SEARCH_DEMO from './bot-search-demo.js';
import COMMAND_BOT_SUMMON_DEMO from './bot-summon-demo.js';
import COMMAND_BOT_TALK_DEMO from './bot-talk-demo.js';
import COMMAND_BOT_TALK from './bot-talk.js';
import Command from './command.js';
import COMMAND_SUM_ADVISE from './sum-advise.js';
import COMMAND_SUM_APOLOGIZE from './sum-apologize.js';
import COMMAND_SUM_BLAME from './sum-blame.js';
import COMMAND_SUM_COMFORT from './sum-comfort.js';
import COMMAND_SUM_COMPLAIN from './sum-complain.js';
import COMMAND_SUM_ENCOURAGE from './sum-encourage.js';
import COMMAND_SUM_LAUGH from './sum-laugh.js';
import COMMAND_SUM_SUM from './sum-sum.js';
import COMMAND_SYS_COMMAND from './sys-command.js';
import COMMAND_SYS_DEPLOY from './sys-deploy.js';
import COMMAND_SYS_DOC from './sys-doc.js';
import COMMAND_SYS_REPORT from './sys-report.js';
import COMMAND_SYS_VERSION from './sys-version.js';
import COMMAND_TRANSLATE_TO_EN from './translate-to-en.js';
import COMMAND_TRANSLATE_TO_JA from './translate-to-ja.js';
import COMMAND_TRANSLATE_TO_CN from './translate-to-cn.js';
import COMMAND_TRANSLATE_TO_GM from './translate-to-gm.js';
import COMMAND_TRANSLATE_TO_EN_DOWN from './translate-to-en-down.js';
import COMMAND_TRANSLATE_TO_JA_DOWN from './translate-to-ja-down.js';
import COMMAND_TRANSLATE_TO_CN_DOWN from './translate-to-cn-down.js';
import COMMAND_TRANSLATE_TO_GM_DOWN from './translate-to-gm-down.js';
import COMMAND_SYS_WRITE from './sys-write.js';//新加的
import COMMAND_SYS_WRITE_INQUIRY from './sys-write-inquiry.js';//新加的
import COMMAND_SYS_WRITE_SALES from './sys-write-sales.js';//新加的
import COMMAND_SYS_WRITE_CONTRACT from './sys-write-contract.js';//新加的
import COMMAND_SYS_WRITE_OVERDUE from './sys-write-overdue.js';//催款信
import COMMAND_SYS_WRITE_ADVERTISE from './sys-write-advertise.js';//廣告信
import COMMAND_SYS_WRITE_THANK from './sys-write-thank.js';//感謝信
import COMMAND_SYS_WRITE_ADVICE from './sys-write-advice.js';
import COMMAND_SYS_MORELETTER from './sys-write-moreletter.js';
import COMMAND_TRANSLATE from './translate.js';
import COMMAND_UP from './up.js';
import COMMAND_DOWN from './down.js';
import COMMAND_REPLY from './sys-reply.js';
import COMMAND_REPLY_UP from './reply-up.js';
import COMMAND_REPLY_DOWN from './reply-down.js';
import COMMAND_EMAIL from './sys-email.js';

export const ALL_COMMANDS = [
  COMMAND_ANALYZE_ANALYZE,
  COMMAND_ANALYZE_LITERARILY,
  COMMAND_ANALYZE_MATHEMATICALLY,
  COMMAND_ANALYZE_NUMEROLOGICALLY,
  COMMAND_ANALYZE_PHILOSOPHICALLY,
  COMMAND_ANALYZE_PSYCHOLOGICALLY,
  COMMAND_BOT_ACTIVATE,
  COMMAND_BOT_CONTINUE,
  COMMAND_BOT_DEACTIVATE,
  COMMAND_BOT_DRAW_DEMO,
  COMMAND_BOT_DRAW,
  COMMAND_BOT_FORGET,
  COMMAND_BOT_RETRY,
  COMMAND_BOT_SEARCH,
  COMMAND_BOT_SUMMON_DEMO,
  COMMAND_BOT_TALK_DEMO,
  COMMAND_BOT_TALK,
  COMMAND_SUM_ADVISE,
  COMMAND_SUM_APOLOGIZE,
  COMMAND_SUM_BLAME,
  COMMAND_SUM_COMFORT,
  COMMAND_SUM_COMPLAIN,
  COMMAND_SUM_ENCOURAGE,
  COMMAND_SUM_LAUGH,
  COMMAND_SUM_SUM,
  COMMAND_SYS_COMMAND,
  COMMAND_SYS_DEPLOY,
  COMMAND_SYS_DOC,
  COMMAND_SYS_REPORT,
  COMMAND_SYS_VERSION,
  COMMAND_TRANSLATE,
  COMMAND_TRANSLATE_TO_EN,
  COMMAND_TRANSLATE_TO_JA,
  COMMAND_TRANSLATE_TO_CN,
  COMMAND_TRANSLATE_TO_GM,
  COMMAND_TRANSLATE_TO_EN_DOWN,
  COMMAND_TRANSLATE_TO_JA_DOWN,
  COMMAND_TRANSLATE_TO_CN_DOWN,
  COMMAND_TRANSLATE_TO_GM_DOWN,
  COMMAND_SYS_WRITE,//新增的
  COMMAND_SYS_WRITE_INQUIRY,//新增的
  COMMAND_SYS_WRITE_SALES,
  COMMAND_SYS_WRITE_CONTRACT,
  COMMAND_SYS_WRITE_OVERDUE,//催款信
  COMMAND_SYS_WRITE_ADVERTISE,//廣告信
  COMMAND_SYS_WRITE_THANK,//感謝信
  COMMAND_SYS_WRITE_ADVICE,
  COMMAND_SYS_MORELETTER,
  COMMAND_UP,
  COMMAND_DOWN,
  COMMAND_REPLY,
  COMMAND_REPLY_UP,
  COMMAND_REPLY_DOWN,
  COMMAND_EMAIL
];

export const INFO_COMMANDS = [
  COMMAND_SYS_VERSION,
  COMMAND_SYS_DOC,
  COMMAND_SYS_REPORT,
];

export const INFO_WRITTING = [
  COMMAND_SYS_WRITE_INQUIRY,//詢問信
  COMMAND_SYS_WRITE_SALES,//銷售信
  COMMAND_SYS_WRITE_CONTRACT,//合約信
  COMMAND_SYS_MORELETTER,
];

export const INFO_UPDOWN = [
  COMMAND_UP,
  COMMAND_DOWN
];

export const INFO_REPLY_UPDOWN = [
  COMMAND_REPLY_UP,
  COMMAND_REPLY_DOWN
];


export const INFO_TRANSLATE_DOWN = [
  COMMAND_TRANSLATE_TO_EN_DOWN,
  COMMAND_TRANSLATE_TO_JA_DOWN,
  COMMAND_TRANSLATE_TO_CN_DOWN,
  COMMAND_TRANSLATE_TO_GM_DOWN,
];

export const INFO_TRANSLATE = [
  COMMAND_TRANSLATE_TO_EN,
  COMMAND_TRANSLATE_TO_JA,
  COMMAND_TRANSLATE_TO_CN,
  COMMAND_TRANSLATE_TO_GM,
];


 export const MORE_LETTER = [
   COMMAND_SYS_WRITE_OVERDUE,//催款信
   COMMAND_SYS_WRITE_ADVERTISE,//廣告信
   COMMAND_SYS_WRITE_THANK,//感謝信
   COMMAND_SYS_WRITE_ADVICE//建議信
 ];

export const GENERAL_COMMANDS = [
  COMMAND_SYS_WRITE_INQUIRY,//詢問信
  COMMAND_SYS_WRITE_SALES,//銷售信
  COMMAND_SYS_WRITE_CONTRACT,//合約信
  COMMAND_SYS_WRITE_OVERDUE,//催款信
  COMMAND_SYS_WRITE_ADVERTISE,//廣告信
  COMMAND_SYS_WRITE_THANK,//感謝信
  COMMAND_SYS_WRITE_ADVICE
];

export const ENQUIRE_COMMANDS = ALL_COMMANDS.filter(({ type }) => (
  type === TYPE_SUM
  || type === TYPE_ANALYZE
  || type === TYPE_TRANSLATE
  || type === TYPE_TRANSLATE_DOWN
));

export {
  COMMAND_ANALYZE_ANALYZE,
  COMMAND_ANALYZE_LITERARILY,
  COMMAND_ANALYZE_MATHEMATICALLY,
  COMMAND_ANALYZE_NUMEROLOGICALLY,
  COMMAND_ANALYZE_PHILOSOPHICALLY,
  COMMAND_ANALYZE_PSYCHOLOGICALLY,
  COMMAND_BOT_ACTIVATE,
  COMMAND_BOT_CONTINUE,
  COMMAND_BOT_DEACTIVATE,
  COMMAND_BOT_DRAW_DEMO,
  COMMAND_BOT_DRAW,
  COMMAND_BOT_FORGET,
  COMMAND_BOT_RETRY,
  COMMAND_BOT_SEARCH,
  COMMAND_BOT_SUMMON_DEMO,
  COMMAND_BOT_TALK_DEMO,
  COMMAND_BOT_TALK,
  Command,
  COMMAND_SUM_ADVISE,
  COMMAND_SUM_APOLOGIZE,
  COMMAND_SUM_BLAME,
  COMMAND_SUM_COMFORT,
  COMMAND_SUM_COMPLAIN,
  COMMAND_SUM_ENCOURAGE,
  COMMAND_SUM_LAUGH,
  COMMAND_SUM_SUM,
  COMMAND_SYS_COMMAND,
  COMMAND_SYS_DEPLOY,
  COMMAND_SYS_DOC,
  COMMAND_SYS_REPORT,
  COMMAND_SYS_VERSION,
  COMMAND_TRANSLATE,
  COMMAND_UP,
  COMMAND_DOWN,
  COMMAND_TRANSLATE_TO_EN,
  COMMAND_TRANSLATE_TO_JA,
  COMMAND_TRANSLATE_TO_CN,
  COMMAND_TRANSLATE_TO_GM,
  COMMAND_TRANSLATE_TO_EN_DOWN,
  COMMAND_TRANSLATE_TO_JA_DOWN,
  COMMAND_TRANSLATE_TO_CN_DOWN,
  COMMAND_TRANSLATE_TO_GM_DOWN,
  COMMAND_SYS_WRITE,//新加的
  COMMAND_REPLY,
  COMMAND_SYS_WRITE_INQUIRY,//新加的
  COMMAND_SYS_WRITE_SALES,
  COMMAND_SYS_WRITE_CONTRACT,
  COMMAND_SYS_WRITE_OVERDUE,//催款信
  COMMAND_SYS_WRITE_ADVERTISE,//廣告信
  COMMAND_SYS_WRITE_THANK,//感謝信
  COMMAND_SYS_WRITE_ADVICE,
  COMMAND_SYS_MORELETTER,
  COMMAND_REPLY_UP,
  COMMAND_REPLY_DOWN,
  COMMAND_EMAIL
  
};
